seed = 42
data_file = "../data/output.txt"
tokenizer = "../data/tokenizer.json"
model_save_path = "../data/model.pth"
test_size = 0.001
dataloader_num_workers = 4
optimizer = "AdamW"
lr = 0.0001
beta1 = 0.9
beta2 = 0.98
weight_decay = 0.1
eps = 1e-5
lr_scheduler = "cosine"
warmup_ratio = 0.06
n_training_steps = 100000
eval_frequency = 1000
device_batch_size = 64
gradient_accumulation_steps = 4
max_length = 128
hidden_size = 512
n_layers = 12
n_heads = 8
embd_pd = 0.1
attn_pd = 0.3
resid_pd = 0.1
